### ISSUE TITLE
New Shaft(v 7.2.20230425) not able to deal with stale element as before (v 6.3.20220808)

### ISSUE THREAD

**Issue by myoussef87** [ShaftHQ/SHAFT_ENGINE#1081]
### Steps to reproduce :
Execute this code 
`        SHAFT.GUI.WebDriver driver = new SHAFT.GUI.WebDriver();
        driver.getDriver().navigate().to("https://stripe-payments-demo.appspot.com/");
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.element().switchToIframe(By.cssSelector("#card-element iframe"));
        driver.element().type(By.name("cardnumber"),"1234");
`

Expected result:
SHAFT should be able to to switch to Iframe and interact with its elements

Actual results :
Get this error "Failed to Type. Root cause: "org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='cardnumber']"}""

> java.lang.AssertionError: Failed to Type. Root cause: "org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='cardnumber']"}"
	at org.testng.Assert.fail(Assert.java:98)
	at com.shaft.tools.io.internal.FailureReporter.fail(FailureReporter.java:32)
	at com.shaft.gui.element.internal.ElementActionsHelper.failAction(ElementActionsHelper.java:919)
	at com.shaft.gui.element.internal.ElementActionsHelper.failAction(ElementActionsHelper.java:852)
	at com.shaft.gui.element.internal.FluentElementActions.type(FluentElementActions.java:902)
	at gui.regression.test2.test(test2.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.AssertionError: zero elements found matching this locator "By.name: cardnumber" Root cause: "org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='cardnumber']"}"
	at org.testng.Assert.fail(Assert.java:98)
	at com.shaft.tools.io.internal.FailureReporter.fail(FailureReporter.java:32)
	at com.shaft.gui.element.internal.ElementActionsHelper.identifyUniqueElement(ElementActionsHelper.java:761)
	at com.shaft.gui.element.internal.ElementActionsHelper.performActionAgainstUniqueElement(ElementActionsHelper.java:737)
	at com.shaft.gui.element.internal.ElementActionsHelper.clearBeforeTyping(ElementActionsHelper.java:586)
	at com.shaft.gui.element.internal.ElementActionsHelper.typeWrapper(ElementActionsHelper.java:703)
	at com.shaft.gui.element.internal.FluentElementActions.type(FluentElementActions.java:889)
	... 32 more
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.shaft.gui.element.internal.ElementActionsHelper$$Lambda$854/0x0000000801203a38@374b1d85 (tried for 60 second(s) with 100 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at com.shaft.gui.element.internal.ElementActionsHelper.waitForElementPresence(ElementActionsHelper.java:158)
	at com.shaft.gui.element.internal.ElementActionsHelper.getMatchingElementsInformation(ElementActionsHelper.java:791)
	at com.shaft.gui.element.internal.ElementActionsHelper.identifyUniqueElement(ElementActionsHelper.java:754)
	... 36 more
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='cardnumber']"}
  (Session info: chrome=112.0.5615.138)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.2.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0af5b183f6d6066b2fecd156521f1685, findElement {using=name, value=cardnumber}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 112.0.5615.138, chrome: {chromedriverVersion: 112.0.5615.49 (bd2a7bcb881c..., userDataDir: C:\Users\moham\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:50888}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50888/devtoo..., se:cdpVersion: 112.0.5615.138, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 60000, script: 30000}, unhandledPromptBehavior: accept and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0af5b183f6d6066b2fecd156521f1685
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at com.shaft.gui.element.internal.ElementActionsHelper.lambda$waitForElementPresence$0(ElementActionsHelper.java:163)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 39 more

### Working code :

`        SHAFT.GUI.WebDriver driver = new SHAFT.GUI.WebDriver();
        driver.getDriver().navigate().to("https://stripe-payments-demo.appspot.com/");
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.element().switchToIframe(By.cssSelector("#card-element iframe"));
        //driver.element().type(By.name("cardnumber"),"1234");
        //driver.getDriver().switchTo().frame(driver.getDriver().findElement(By.cssSelector("#card-element iframe")));
        //driver.getDriver().findElement(By.name("cardnumber")).sendKeys("4242424242424242");

        Actions action = new Actions(driver.getDriver());
        action.moveToElement(driver.getDriver().findElement(By.name("cardnumber"))).sendKeys("4242424242424242").perform();
`

### Notes :

Before (v 6.3.20220808) I was able to switch to iFrame and interact with its elements(including Stale elements) using SHAFT 
Now (v 7.2.20230425)  , I have to use Native selenium Action class to interact with iframe elements.

I don't know how to view shaft code from different versions to compare the difference.

Before Code  (v 6.3.20220808) :

`driver.get().switchTo().frame(driver.get().findElement(frmBankForm));
        ElementActions.click(driver.get(),txtBankSearch);`

After Code (v 7.2.20230425) :

`driver.get().switchTo().frame(driver.get().findElement(frmBankForm));
        driver.get().element().click(txtBankSearch);`

and I have to use Action Class to interact with that element again.

  
Here is the discussion details in this thread : https://shaft-engine.slack.com/archives/CTWG4AA0P/p1682682680076379

**Comment by MohabMohie** [comment]
Issue confirmed.
This native code block works:
```java
@Test()
public void switchToIframeAndAssertContent_native_standard() {
    var nativeWebDriver = new ChromeDriver();
    nativeWebDriver.navigate().to(testPage);
    nativeWebDriver.switchTo().frame(nativeWebDriver.findElement(iframe_1));
    var actualText = nativeWebDriver.findElement(nestedElement).getText();
    Assert.assertEquals(actualText, "SHAFT User Guide");
}
```

While this SHAFT code doesn't work:
```java
@Test()
public void switchToIframeAndAssertContent() {
    driver.browser().navigateToURL(testPage)
            .and().element().switchToIframe(iframe_1)
            .and().assertThat(nestedElement).text().isEqualTo("SHAFT User Guide").perform();
}
```
Timing out with an "Element Not Found Exception"

**Comment by MohabMohie** [comment]
Suspect identified as follows: "Engine is converging to use the centralized driver instance, but is not updating it after switching the search context to dive inside the frame."
Investigating to confirm root cause and identify potential fixes.
