### ISSUE TITLE
[Bug]: Percy integration

### ISSUE THREAD

**Issue by MhmdElGazzar** [ShaftHQ/SHAFT_ENGINE#1201]
**Describe the bug**
 I tried to integrate percy 
I did with native selenium , it worked 
upgraded to shaft, faced those errors 
so shaft is the only new thing in this step 
hope it helps 
-------------------------------------------------------------------------------
Test set: SdkTest
-------------------------------------------------------------------------------
Tests run: 14, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.139 sec <<< FAILURE!
testTeardown(SdkTest)  Time elapsed: 1.935 sec  <<< FAILURE!
java.lang.NoSuchFieldError: LOG
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.close(JdkHttpClient.java:307)
	at org.openqa.selenium.devtools.Connection.close(Connection.java:190)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:279)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.call(WebDriverDecorator.java:247)
	at org.openqa.selenium.support.decorators.DefaultDecorated.call(DefaultDecorated.java:48)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:309)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$GD31euBg.quit(Unknown Source)
	at SdkTest.testTeardown(SdkTest.java:40)

engineTeardown(com.shaft.listeners.internal.ConfigurationHelper)  Time elapsed: 2.217 sec  <<< FAILURE!
java.lang.NoSuchFieldError: LOG
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.close(JdkHttpClient.java:307)
	at org.openqa.selenium.devtools.Connection.close(Connection.java:190)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:279)
	at com.shaft.driver.internal.DriverFactoryHelper.closeDriver(DriverFactoryHelper.java:132)
	at com.shaft.driver.DriverFactory.closeAllDrivers(DriverFactory.java:242)
	at com.shaft.listeners.internal.ConfigurationHelper.cleaningOrphanedDriverInstances(ConfigurationHelper.java:38)
	at com.shaft.listeners.internal.ConfigurationHelper.engineTeardown(ConfigurationHelper.java:24)

**Link to SHAFT_Engine Console logs**
[WARNING] The POM for io.percy:percy-java-selenium:jar:2.0.0-beta.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!

**Link to SHAFT_Engine Extent Report HTML**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]
 4. Desktop Browser (if applicable): [e.g. chrome, safari]
 5. Desktop Browser Version (if applicable): [e.g. 22]
 6. Mobile Device Name (if applicable): [e.g. iPhone6]
 7. Mobile Device OS (if applicable): [e.g. iOS8.1]
 8. Mobile Device Browser or Native App: 
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari]
 10. Mobile Device Browser Version (if applicable): [e.g. 22]

**To Reproduce**

**Expected behavior**

**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.

**Additional context**

Add any other relevant context about the problem here.

**Comment by MohabMohie** [comment]
please note that this issue is not reproducible using the latest engine version.
kindly upgrade and feel free to reopen with a fresh stacktrace.
