### ISSUE TITLE
[Bug]: The Safari instance is already paired with another WebDriver session

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#1548]
```java
Driver Factory Action "createNewLocalDriverInstance" failed. With the following test data "Failed to create new Browser Session". Root cause: "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not create a session: The Safari instance is already paired with another WebDriver session. "

      java.lang.AssertionError: Driver Factory Action "createNewLocalDriverInstance" failed. With the following test data "Failed to create new Browser Session". Root cause: "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not create a session: The Safari instance is already paired with another WebDriver session. "
at org.testng.Assert.fail(Assert.java:99)
at com.shaft.tools.io.internal.FailureReporter.fail(FailureReporter.java:38)
at com.shaft.driver.internal.DriverFactory.DriverFactoryHelper.failAction(DriverFactoryHelper.java:110)
at com.shaft.driver.internal.DriverFactory.DriverFactoryHelper.createNewLocalDriverInstance(DriverFactoryHelper.java:379)
at com.shaft.driver.internal.DriverFactory.DriverFactoryHelper.initializeDriver(DriverFactoryHelper.java:598)
at com.shaft.driver.internal.DriverFactory.DriverFactoryHelper.initializeDriver(DriverFactoryHelper.java:554)
at com.shaft.driver.DriverFactory.getHelper(DriverFactory.java:109)
at com.shaft.driver.SHAFT$GUI$WebDriver.<init>(SHAFT.java:42)
at testPackage.ChainableElementActionsTests.beforeMethod(ChainableElementActionsTests.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not create a session: The Safari instance is already paired with another WebDriver session. 
Host info: host: 'Mac-1711185861525.local', ip: 'fe80:0:0:0:ca9:270c:8120:39f1%en0'
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.7.3', java.version: '21.0.2'
Driver info: org.openqa.selenium.safari.SafariDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: safari, pageLoadStrategy: normal, timeouts: {pageLoad: 60000, script: 60000}, unhandledPromptBehavior: ignore}]}]
Capabilities {browserName: safari, pageLoadStrategy: normal, timeouts: {pageLoad: 60000, script: 60000}, unhandledPromptBehavior: ignore}
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:162)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:84)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:80)
at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:57)
at com.shaft.driver.internal.DriverFactory.DriverFactoryHelper.createNewLocalDriverInstance(DriverFactoryHelper.java:305)
... 25 more
```

**Comment by MohabMohie** [comment]
Recurred in the nightly **Local E2E Tests** workflow (issue #3987), stable across all 4 tracked nights (2026-07-22 through 2026-07-25), always in `MacOSX_Safari_Local`.

Latest occurrence: run [30143597510](https://github.com/ShaftHQ/SHAFT_ENGINE/actions/runs/30143597510), job `MacOSX_Safari_Local` (89641308759):

```
| broken | `testPackage.mockedTests.GuiVerificationTests.beforeMethod` | Driver Factory Action "createNewLocalDriverInstance" failed. With the following test data "Failed to create new Browser Session". Root cause: "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not create a session: The Safari instance is already paired with another WebDriver session. "
```

Several other, seemingly-unrelated `testPackage.mockedTests.*`/`GUIWizardTests`/`E2ECoverageTests` methods in the same run also break/fail downstream of this — consistent with one earlier test in the sequential run leaking its Safari session (never reaching `driver.quit()`), which then blocks every later `safaridriver` session-creation attempt for the rest of the JVM fork (safaridriver only allows one active WebDriver session system-wide).

Note: this job's log is currently dominated by a separate, much larger `java.lang.OutOfMemoryError: Java heap space` cascade (see #3930/#3942 and the newly filed heap-sizing follow-up) which may itself be contributing to or masking the exact leak site — recommend re-triaging which specific earlier test leaks the session once the heap issue is resolved and the run can complete without cascading OOM noise.

Filed while diagnosing #3987 (Local E2E Tests nightly failure), not fixed — read-only diagnosis pass, no code changes made.
