### ISSUE TITLE
OpenCV issue java.lang.UnsatisfiedLinkError: 'long org.opencv.core.Mat.n_Mat()' - Linux 

### ISSUE THREAD

**Issue by HaithamGitHub** [ShaftHQ/SHAFT_ENGINE#640]
**Describe the bug**
got openCV issue java.lang.UnsatisfiedLinkError: 'long org.opencv.core.Mat.n_Mat()' during execution locally on Linux 

**To Reproduce**
run test case from Jenkins on Linux redhat

**Desktop (please complete the following information):**
 - OS: linux redhat
 - Browser [chrome]
 - Version [ 87.0.4280.88 ]

**Additional context**

==========================================================================
Detected SHAFT Engine Version: "6.2.20220609"

[ReportManager] Attempting to run locally on: "Linux-64 | GoogleChrome", Headless Execution. @22-06-2022 11:18:32.0852 AM
Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 60562
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jun 22, 2022 11:18:33 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Jun 22, 2022 11:18:33 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 87, so returning the closest version found: 85
Jun 22, 2022 11:18:33 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 87 of 85
[ReportManager] Successfully Opened Google Chrome. @22-06-2022 11:18:33.0062 AM

java.lang.UnsatisfiedLinkError: 'long org.opencv.core.Mat.n_Mat()'
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:23)
	at org.opencv.core.MatOfByte.<init>(MatOfByte.java:34)
	at com.shaft.gui.image.ImageProcessingActions.highlightElementInScreenshot(ImageProcessingActions.java:142)
	at com.shaft.gui.image.ScreenshotManager.internalCaptureScreenShot(ScreenshotManager.java:447)
	at com.shaft.gui.image.ScreenshotManager.captureScreenShot(ScreenshotManager.java:143)
	at com.shaft.gui.element.WebDriverElementActions.takeScreenshot(WebDriverElementActions.java:1374)
	at com.shaft.gui.element.WebDriverElementActions.reportActionResult(WebDriverElementActions.java:1728)
	at com.shaft.gui.element.WebDriverElementActions.passAction(WebDriverElementActions.java:1585)
	at com.shaft.gui.element.WebDriverElementActions.passAction(WebDriverElementActions.java:1352)
	at com.shaft.gui.element.WebDriverElementActions.type(WebDriverElementActions.java:1171)
	at com.shaft.gui.element.ElementActions.type(ElementActions.java:548)
	at pages.LoginPage.checkLogin(LoginPage.java:92)
	at pages.LoginPage.ValidLogin(LoginPage.java:131)
	at testcases.UserTests.CheckEnv(UserTests.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] testcases.UserTests.CheckEnv
[INFO]   Run 1: PASS
[ERROR]   Run 2: UserTests.CheckEnv:93 » UnsatisfiedLink 'long org.opencv.core.Mat.n_Mat()'
[INFO] 
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.

**Comment by MohabMohie** [comment]
potential dry fix implemented and will be pushed with the coming release.
