### ISSUE TITLE
[Bug] Parallelized or Sequential running issue

### ISSUE THREAD

**Issue by sultanpaymob** [ShaftHQ/SHAFT_ENGINE#748]
**Describe the bug**
thanks for finding the below error once when trying to run the test Parallelized or Sequential.

**To Reproduce**
ExecutionPlatform.properties:

SHAFT.CrossBrowserMode=parallelized
executionAddress=dockerized
targetOperatingSystem=Linux
com.SHAFT.proxySettings=

**Error Log**
2022-10-24 23:24:50.840  INFO [@497 - main] com.shaft.tools.io.ReportManager : File Action "DoesFileExist" successfully performed. With the following test data "File Path: "target/downloadedFiles/"".
2022-10-24 23:24:50.841  INFO [@497 - main] com.shaft.tools.io.ReportManager : File Action "GetAbsolutePath" successfully performed. With t
<img width="1267" alt="Screenshot 2022-10-24 at 11 38 55 PM" src="https://user-images.githubusercontent.com/109296848/197634865-2b01af91-732a-425d-84ae-0d91263f49b8.png">
he following test data "Relative Folder Path: "src/test/resources/testDataFiles/target/downloadedFiles/"".
2022-10-24 23:24:50.852  INFO [@514 - main] com.shaft.tools.io.ReportManager : Attempting to run dockerized on: "Linux | Google chrome".
2022-10-24 23:24:50.855  INFO [@497 - main] com.shaft.tools.io.ReportManager : Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--start-maximized], extensions: [], prefs: {download.default_directory: /Users/sultan/IdeaProjects/..., download.prompt_for_download: false, profile.default_content_settings.popups: 0}}, pageLoadStrategy: normal, platformName: LINUX, timeouts: {pageLoad: 30000, script: 30000}, unhandledPromptBehavior: accept and notify}
2022-10-24 23:24:50.856  INFO [@497 - main] com.shaft.tools.io.ReportManager : Identifying target OS/Browser and setting up the dockerized environment automatically. Please note that if a new docker container will be downloaded it may take some time...
2022-10-24 23:24:55.085  INFO [@330 - main] io.github.bonigarcia.wdm.docker.DockerService : Pulling Docker image selenoid/vnc:chrome_106.0 (this might take some time, but only the first time)
2022-10-24 23:24:58.143  INFO [@177 - main] io.github.bonigarcia.wdm.docker.DockerService : Starting Docker container selenoid/vnc:chrome_106.0
Oct 24, 2022 11:25:02 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
2022-10-24 23:25:31.536  INFO [@497 - main] com.shaft.tools.io.ReportManager : Successfully created attachment "Exception Stack Trace - io.github.bonigarcia.wdm.config.WebDriverManagerException"
2022-10-24 23:25:31.542 ERROR [@609 - main] io.qameta.allure.AllureLifecycle : Could not add attachment: no test is running
2022-10-24 23:25:31.543  INFO [@497 - main] com.shaft.tools.io.ReportManager : Successfully created attachment "SHAFT Engine Logs - Current Method log: setUp"

java.lang.AssertionError: Driver Factory Action "createNewDockerizedDriverInstance" failed. With the following test data "Failed to create new Dockerized Browser Session, are you sure Docker is available on your machine?".

	at org.testng.Assert.fail(Assert.java:98)
	at com.shaft.driver.DriverFactoryHelper.failAction(DriverFactoryHelper.java:144)
	at com.shaft.driver.DriverFactoryHelper.createNewDockerizedDriverInstance(DriverFactoryHelper.java:391)
	at com.shaft.driver.DriverFactoryHelper.initializeDriver(DriverFactoryHelper.java:577)
	at com.shaft.driver.DriverFactoryHelper.initializeDriver(DriverFactoryHelper.java:548)
	at com.shaft.driver.DriverFactory.getDriver(DriverFactory.java:24)
	at com.shaft.driver.SHAFT$GUI$WebDriver.<init>(SHAFT.java:31)
	at com.paymob.gui.tests.test.setUp(test.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: There was an error creating WebDriver object for Chrome
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1774)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:424)
	at com.shaft.driver.DriverFactoryHelper.createNewDockerizedDriverInstance(DriverFactoryHelper.java:386)
	... 30 more
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: Timeout of 30 seconds creating WebDriver object
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:95)
	at io.github.bonigarcia.wdm.WebDriverManager.createDockerWebDriver(WebDriverManager.java:1896)
	at io.github.bonigarcia.wdm.WebDriverManager.instantiateDriver(WebDriverManager.java:1754)
	... 32 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'MSultans-MacBook.local', ip: 'fe80:0:0:0:cfe:8989:5677:841c%en0'
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.0', java.version: '17.0.4.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --start-maximized], extensions: [], prefs: {download.default_directory: /Users/sultan/IdeaProjects/..., download.prompt_for_download: false, profile.default_content_settings.popups: 0}}, pageLoadStrategy: normal, platformName: LINUX, timeouts: {pageLoad: 30000, script: 30000}, unhandledPromptBehavior: accept and notify}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --start-maximized], extensions: [], prefs: {download.default_directory: /Users/sultan/IdeaProjects/..., download.prompt_for_download: false, profile.default_content_settings.popups: 0}}, pageLoadStrategy: normal, platformName: LINUX, timeouts: {pageLoad: 30000, script: 30000}, unhandledPromptBehavior: accept and notify}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at io.github.bonigarcia.wdm.webdriver.WebDriverCreator.createRemoteWebDriver(WebDriverCreator.java:89)
	... 34 more

**Comment by MohabMohie** [comment]
Question, in this test are you trying to download a file?

**Comment by sultanpaymob** [comment]
no, it's a normal setup driver
    @BeforeClass
    public void setUp() {
        driver = new SHAFT.GUI.WebDriver();
        TestDataJSON = new SHAFT.TestData.JSON("TestDataJSON.json");
        LoginPage_Obj = new A1_LoginPage(driver);}

**Comment by MohabMohie** [comment]
Interesting... This needs closer investigation...
Will keep you updated

**Comment by MohabMohie** [comment]
I am unfortunately unable to reproduce this exact issue on any of my machines, however it looks like a Docker Desktop related issue. Have you investigated the type of container and the containerization/virtualization settings needed for your Mac device?
