### ISSUE TITLE
[Bug] waitToBeReady() is not working properly in version 7.1.20230210

### ISSUE THREAD

**Issue by SondosSaber** [ShaftHQ/SHAFT_ENGINE#863]
**Issue**
waitToBeReady() is not working properly in veriosn 7.1.20230210 while it was working correctly in version 7.1.20230116

**To Reproduce**
1. try to use the waitToBeReady for a ceratin element to be displayed on UI 

**Expected behavior**
engine should perform the wait until the element is visible but the engine is not waiting in version 7.1.20230210

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 109.0.5414.120 

**Attachement**
Logs of the failure in version 7.1.20230210
Failed to Wait for element to be present "waited for the element's state of visibility to be (true). Element locator (By.xpath: //p[@data-testid='findCustomer-text'])".
java.lang.AssertionError: Failed to Wait for element to be present "waited for the element's state of visibility to be (true). Element locator (By.xpath: //p[@data-testid='findCustomer-text'])".
	at org.testng.Assert.fail(Assert.java:98)
	at io.github.shafthq.shaft.gui.element.ElementActionsHelper.failAction(ElementActionsHelper.java:772)
	at io.github.shafthq.shaft.gui.element.ElementActionsHelper.failAction(ElementActionsHelper.java:712)
	at com.shaft.gui.element.ElementActions.waitForElementToBePresent(ElementActions.java:1196)
	at io.github.shafthq.shaft.gui.element.FluentElementActions.waitToBeReady(FluentElementActions.java:479)
	at pages.AgentDashboardPage.navigateToCustomerSearchPage(AgentDashboardPage.java:65)
	at CustomerSearchTests.validateSearchingCustomerViaMsisdn(CustomerSearchTests.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.AssertionError: Failed to Wait for element to be present "waited for the element's state of visibility to be (true). Element locator (By.xpath: //p[@data-testid='findCustomer-text'])" against "By.xpath: //p[@data-testid='findCustomer-text']".
	at org.testng.Assert.fail(Assert.java:110)
	at io.github.shafthq.shaft.gui.element.ElementActionsHelper.failAction(ElementActionsHelper.java:774)
	at io.github.shafthq.shaft.gui.element.ElementActionsHelper.failAction(ElementActionsHelper.java:712)
	at com.shaft.gui.element.ElementActions.waitForElementToBePresent(ElementActions.java:1188)
	... 30 more

**Comment by SondosSaber** [comment]
unfortunately  the issue is still happening as there is no any type of wiat is performing while it was working fine in this version 
7.1.202030116

We are implementing the following:

    public CustomerSearchPage navigateToCustomerSearchPage(){
        new ElementActions(driver.get())
//                .waitToBeInvisible(GenericLoaders.globalLoader())
                .waitToBeReady(customerSearchCard())
                .click(customerSearchCard());
        return new CustomerSearchPage(driver);
    }

new LoginPage(driver)
                .performLoginHttps(agentWithMultiStoresUser, agentWithMultiStoresPassword)
                .navigateToCustomerSearchPage()
                .searchCustomer("msisdnCLITab", msisdn);
